const {createRequire}=require('node:module');
const {mkdirSync,writeFileSync}=require('node:fs');
const path=require('node:path');
const runtimeRequire=createRequire('/Users/baizijing/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/runtime.cjs');
const {chromium}=runtimeRequire('playwright');
const output=path.join(__dirname,'..','docs','evidence','revision-21');mkdirSync(output,{recursive:true});
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],checks=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  try {
    await page.goto('http://127.0.0.1:4173/web-preview/');
    await page.locator('#promptProject').filter({hasText:'目前專案'}).waitFor();
    await page.locator('#appVersion').filter({hasText:'V1.4'}).waitFor();
    await page.locator('#apiStatusText').filter({hasText:'未連結'}).waitFor();
    if(!(await page.locator('#apiStatusDot').getAttribute('class')).includes('api-unconfigured'))throw Error('Expected red unconfigured API indicator');
    if(await page.locator('[data-page]').count()!==4)throw Error('Expected four navigation entries');
    if(await page.locator('[data-template]').count()!==6)throw Error('Missing starter templates');
    await page.locator('[data-template="0"]').click();
    if(!(await page.inputValue('#promptContent')).includes('驗收標準'))throw Error('Template not applied');
    await page.click('#promptSave');await page.locator('#promptVersion').filter({hasText:'v1'}).waitFor();
    await page.click('#promptNew');
    if(await page.inputValue('#promptContent'))throw Error('Blank draft should be empty');
    await page.locator('.cloud-analysis summary').click();await page.click('#cloudAnalyze');
    await page.locator('#cloudAnalysisStatus').filter({hasText:'瀏覽器不發送'}).waitFor();
    await page.click('[data-page="settings"]');
    if(!await page.locator('#cloudKey').isDisabled())throw Error('Browser must not collect real API keys');
    await page.click('[data-page="prompts"]');checks.push('version V1.4 and unconfigured API indicator, six templates, save as own copy, new blank draft, browser API safety');
    await page.fill('#promptTitle','測試範本');await page.fill('#promptContent','請保留限制並整理研究資料。');await page.click('#promptSave');
    await page.locator('#promptVersion').filter({hasText:'v1'}).waitFor();
    await page.selectOption('#usageTool','claude');await page.locator('#usageModel').filter({hasText:'Sonnet'}).waitFor();
    await page.selectOption('#usageTool','local');await page.locator('#usageLevel').filter({hasText:'不適用'}).waitFor();
    await page.selectOption('#usageTool','codex');checks.push('prompt save and tool guidance');
    await page.click('[data-page="projects"]');
    const descriptions=await page.locator('.file-description').allTextContents();
    if(descriptions.length!==5||descriptions.some(text=>!text.trim()))throw Error('Missing file purpose descriptions');
    if(!descriptions.some(text=>text.includes('AI 協作規則')))throw Error('Missing AGENTS purpose');
    checks.push('file purpose under each filename');
    for(const group of ['核心記憶','專案提示詞','專案技能','AI 輸出項目'])await page.locator('.file-group').filter({hasText:group}).waitFor();
    const outputGroup=page.locator('.file-group').filter({hasText:'AI 輸出項目'});
    await outputGroup.locator('xpath=following-sibling::tr[1]').locator('.file-description').filter({hasText:'AI 提示詞視覺化管理 App'}).waitFor();
    for(const file of ['AGENTS.md','docs/decisions.md','.agents/skills/review/SKILL.md']){
      await page.click(`[data-preview-file="${file}"]`);await page.click('#editFileButton');await page.locator('#fileEditor[open]').waitFor();
      const original=await page.inputValue('#editorText');
      await page.locator('#editorAdvanced summary').click();
      await page.fill('#editorText',original+'\n## 驗收內容\n\n新內容 <script>literal text</script>\n');
      await page.click('#editorPreview');await page.waitForFunction(()=>!document.querySelector('#editorSave').disabled);
      await page.click('#editorSave');await page.locator('#editorStatus').filter({hasText:'已儲存'}).waitFor();await page.click('#editorClose');
      await page.locator('#filePreview').filter({hasText:'新內容'}).waitFor();checks.push(`edit and save ${file}`);
    }
    await page.locator('[data-restore-id]').first().click();await page.waitForTimeout(200);
    await page.click('[data-preview-file=".agents/skills/review/SKILL.md"]');
    if((await page.locator('#filePreview').textContent()).includes('新內容'))throw Error('Restore did not revert file');
    checks.push('restore last edit');
    await page.click('[data-page="health"]');await page.click('[data-health-file="docs/health-demo.md"]');
    await page.locator('.health-line.flagged').first().waitFor();
    if(await page.locator('.health-line.flagged').count()<4)throw Error('Missing health highlights');
    if(!await page.locator('.health-folder-group h4').filter({hasText:'專案資料夾：AI Memory Manager/docs'}).count())throw Error('Missing folder grouping');
    if(await page.locator('.health-type.prompts').filter({hasText:'專案提示詞'}).count()<1)throw Error('Missing prompt type badge');
    if(await page.locator('.health-issue-count').filter({hasText:'項待確認'}).count()<1)throw Error('Missing filled issue count');
    if((await page.locator('.health-file').first().textContent()).includes('更新：'))throw Error('Old update label remains');
    checks.push('health grouping, type badge, last-updated label and line highlights');
    await page.click('[data-page="projects"]');await page.click('[data-preview-file="AGENTS.md"]');await page.click('#editFileButton');
    await page.locator('#fileEditor[open]').waitFor();
    if(await page.locator('#editorTemplate').count())throw Error('Suggested section should be removed');
    await page.fill('#editorNewTitle','新章節測試');await page.fill('#editorNewContent','保留中文、條列與 <script>literal</script>。');
    await page.click('#editorPreview');await page.locator('#editorError').filter({hasText:'未加入'}).waitFor();
    await page.click('#editorInsert');await page.locator('#editorContentPreview').filter({hasText:'## 新章節測試'}).waitFor();
    if(await page.locator('#editorContentPreview script').count())throw Error('Preview executed HTML');
    await page.fill('#editorNewTitle','新章節測試');await page.fill('#editorNewContent','duplicate');await page.click('#editorInsert');
    await page.locator('#editorError').filter({hasText:'已存在'}).waitFor();
    await page.fill('#editorNewTitle','');await page.fill('#editorNewContent','');await page.click('#editorPreview');
    await page.waitForFunction(()=>!document.querySelector('#editorSave').disabled);
    await page.click('#editorExtract');await page.waitForFunction(()=>!document.querySelector('#fileEditor').open);
    if(!(await page.inputValue('#promptContent')).includes('新章節測試'))throw Error('Extraction lost current draft');
    if(!(await page.inputValue('#promptContent')).includes('來源：AGENTS.md'))throw Error('Extraction lost source');
    await page.click('#promptSave');await page.locator('#promptVersion').filter({hasText:'v1'}).waitFor();
    await page.click('[data-page="projects"]');await page.click('[data-preview-file="AGENTS.md"]');
    if((await page.locator('#filePreview').textContent()).includes('新章節測試'))throw Error('Extraction wrote project file');
    checks.push('new section validation, content preview, extraction to saved template without file write');
    const dimensions=[];
    for(const width of [1440,1180,980,820,768,560,390]){
      await page.setViewportSize({width,height:1000});
      for(const name of ['prompts','projects','health','settings']){
        await page.click(`[data-page="${name}"]`);await page.waitForTimeout(220);
        const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
        if(size.scroll>width+1)throw Error(`Overflow ${name} ${width}: ${size.scroll}`);
        dimensions.push({page:name,...size});
        if([1440,980,390].includes(width))await page.screenshot({path:path.join(output,`${name}-${width}.png`),fullPage:true});
      }
      await page.click('[data-page="projects"]');await page.click('[data-preview-file="AGENTS.md"]');await page.click('#editFileButton');
      const box=await page.locator('#fileEditor').boundingBox();if(box.x<0||box.x+box.width>width+1)throw Error(`Dialog overflow ${width}`);
      await page.selectOption('#editorSection',{label:'專案協作規則'});await page.fill('#editorSectionText','- 更新協作規則。');await page.click('#editorSectionApply');await page.click('#editorPreview');
      await page.waitForFunction(()=>!document.querySelector('#editorSave').disabled);
      await page.locator('#editorSave').scrollIntoViewIfNeeded();
      if([1440,980,390].includes(width))await page.screenshot({path:path.join(output,`editor-${width}.png`),fullPage:true});
      await page.keyboard.press('Escape');
    }
    await page.setViewportSize({width:1440,height:1000});
    await page.click('[data-page="prompts"]');await page.reload();await page.locator('[data-prompt-id]').first().waitFor();await page.locator('[data-prompt-id]').first().click();
    await page.locator('#promptVersion').filter({hasText:'v1'}).waitFor();
    if(errors.length)throw Error(errors.join('\n'));
    writeFileSync(path.join(output,'web-tests.json'),JSON.stringify({passed:true,checks,dimensions,errors},null,2));
    console.log(JSON.stringify({passed:true,checks,layoutChecks:dimensions.length}));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
